'use client'

import { useMemo, useState } from 'react'
import {
  Activity, ArrowUpRight, BarChart3, Bell, Check, ChevronDown, ChevronRight,
  CircleAlert, Clock3, FileText, Filter, Inbox, LayoutDashboard, Loader2,
  Mail, Menu, MoreHorizontal, Plus, Search, Send, Settings, Sparkles,
  Upload, Users, X, Zap,
} from 'lucide-react'

type PageKey = 'Dashboard' | 'Recipients' | 'Campaigns' | 'History'
type Status = 'Delivered' | 'Pending' | 'Failed' | 'New' | 'Updated' | 'Invalid'

const recipients = [
  { name: 'Olivia Martin', email: 'olivia.martin@northstar.io', status: 'New' as Status, contacted: 'Never', added: 'Aug 22, 2026' },
  { name: 'Liam Johnson', email: 'liam.johnson@acme.co', status: 'Updated' as Status, contacted: 'Aug 20, 2026', added: 'Aug 21, 2026' },
  { name: 'Sophia Williams', email: 'sophia.w@northstar.io', status: 'Delivered' as Status, contacted: 'Aug 18, 2026', added: 'Aug 19, 2026' },
  { name: 'Noah Brown', email: 'noah.brown@vertex.com', status: 'New' as Status, contacted: 'Never', added: 'Aug 19, 2026' },
  { name: 'Emma Davis', email: 'emma.davis@acme.co', status: 'Invalid' as Status, contacted: 'Never', added: 'Aug 17, 2026' },
  { name: 'James Wilson', email: 'james.wilson@lumina.dev', status: 'Delivered' as Status, contacted: 'Aug 16, 2026', added: 'Aug 16, 2026' },
]
const campaigns = [
  { name: 'August product update', subject: 'What’s new in MailFlow', recipients: 482, sent: 476, failed: 6, status: 'Completed', date: 'Aug 22, 2026' },
  { name: 'Customer check-in', subject: 'How are things going?', recipients: 128, sent: 128, failed: 0, status: 'Completed', date: 'Aug 18, 2026' },
  { name: 'Early access invite', subject: 'You’re invited to try the new workspace', recipients: 84, sent: 81, failed: 3, status: 'Completed', date: 'Aug 12, 2026' },
]
const history = [
  { recipient: 'Olivia Martin', email: 'olivia.martin@northstar.io', campaign: 'August product update', status: 'Pending' as Status, at: 'Today, 2:42 PM' },
  { recipient: 'Sophia Williams', email: 'sophia.w@northstar.io', campaign: 'August product update', status: 'Delivered' as Status, at: 'Today, 2:42 PM' },
  { recipient: 'James Wilson', email: 'james.wilson@lumina.dev', campaign: 'August product update', status: 'Delivered' as Status, at: 'Today, 2:41 PM' },
  { recipient: 'Emma Davis', email: 'emma.davis@acme.co', campaign: 'August product update', status: 'Failed' as Status, at: 'Today, 2:41 PM' },
  { recipient: 'Liam Johnson', email: 'liam.johnson@acme.co', campaign: 'Customer check-in', status: 'Delivered' as Status, at: 'Aug 18, 2026' },
]

function StatusPill({ status }: { status: string }) {
  const tone = status === 'Delivered' || status === 'Completed' || status === 'New' ? 'success' : status === 'Failed' || status === 'Invalid' ? 'danger' : 'neutral'
  return <span className={`status-pill ${tone}`}><span className="status-dot" />{status}</span>
}
function StatCard({ icon: Icon, label, value, detail, tone = '' }: any) {
  return <div className="stat-card"><div className={`stat-icon ${tone}`}><Icon size={18} /></div><div><p className="eyebrow">{label}</p><p className="stat-value">{value}</p><p className="stat-detail">{detail}</p></div></div>
}
function Topbar({ title, onMenu, onCreate }: { title: string; onMenu: () => void; onCreate: () => void }) {
  return <header className="topbar"><button className="mobile-menu" onClick={onMenu} aria-label="Open navigation"><Menu size={20} /></button><div><p className="breadcrumb">Workspace <ChevronRight size={13} /> {title}</p><h1>{title}</h1></div><div className="top-actions"><button className="icon-button" aria-label="Notifications"><Bell size={18} /><span className="notification-dot" /></button><button className="avatar">JD</button><button className="primary-button" onClick={onCreate}><Plus size={17} /> Create campaign</button></div></header>
}
function Dashboard({ onCreate }: { onCreate: () => void }) {
  return <><div className="welcome-row"><div><p className="muted">Saturday, August 23, 2026</p><h2>Good afternoon, Jamie</h2><p className="muted">Here’s what’s happening with your email activity.</p></div><button className="secondary-button" onClick={onCreate}><Sparkles size={16} /> Start a campaign</button></div><div className="stats-grid"><StatCard icon={Users} label="Total recipients" value="1,284" detail="+12 this week" tone="blue" /><StatCard icon={Zap} label="New recipients" value="12" detail="Since last sync" tone="violet" /><StatCard icon={Send} label="Emails sent" value="2,846" detail="+18.4% this month" tone="green" /><StatCard icon={CircleAlert} label="Failed" value="24" detail="0.8% failure rate" tone="orange" /></div><div className="content-grid"><section className="panel campaign-panel"><div className="panel-heading"><div><h3>Recent campaigns</h3><p>Keep an eye on your latest sends.</p></div><button className="text-button">View all <ArrowUpRight size={15} /></button></div><div className="campaign-list">{campaigns.map((c) => <div className="campaign-row" key={c.name}><div className="campaign-mark"><Mail size={18} /></div><div className="campaign-info"><strong>{c.name}</strong><span>{c.subject}</span></div><div className="campaign-metric"><b>{c.recipients}</b><span>Recipients</span></div><div className="campaign-metric hide-mobile"><b>{c.sent}</b><span>Sent</span></div><StatusPill status={c.status} /><span className="row-date">{c.date}</span><MoreHorizontal size={18} className="more" /></div>)}</div></section><section className="panel activity-panel"><div className="panel-heading"><div><h3>Recent activity</h3><p>Latest updates from your workspace.</p></div><Activity size={18} className="muted-icon" /></div><div className="activity-list"><div className="activity-item"><div className="activity-icon green"><Check size={15} /></div><div><strong>Campaign sent successfully</strong><span>August product update · 2 minutes ago</span></div></div><div className="activity-item"><div className="activity-icon violet"><Users size={15} /></div><div><strong>12 new recipients found</strong><span>Recipient list synced · 10 minutes ago</span></div></div><div className="activity-item"><div className="activity-icon orange"><CircleAlert size={15} /></div><div><strong>6 emails failed to deliver</strong><span>August product update · 12 minutes ago</span></div></div></div></section></div></>
}
function RecipientsPage() {
  const [query, setQuery] = useState(''); const [filter, setFilter] = useState('All'); const [syncing, setSyncing] = useState(false); const [synced, setSynced] = useState('10 minutes ago')
  const rows = useMemo(() => recipients.filter(r => `${r.name} ${r.email}`.toLowerCase().includes(query.toLowerCase()) && (filter === 'All' || r.status === filter)), [query, filter])
  function sync() { setSyncing(true); setTimeout(() => { setSyncing(false); setSynced('just now') }, 1000) }
  return <><div className="page-intro"><div><h2>Recipients</h2><p className="muted">Manage and synchronize your recipient list.</p></div><div className="button-row"><button className="secondary-button"><Upload size={16} /> Upload list</button><button className="primary-button" onClick={sync} disabled={syncing}>{syncing ? <Loader2 className="spin" size={16} /> : <Zap size={16} />} {syncing ? 'Syncing...' : 'Sync recipients'}</button></div></div><div className="sync-note"><Check size={15} /> Last synced {synced} <span>·</span> <b>12 new recipients found</b></div><div className="mini-stats"><div><span>Total</span><b>1,284</b></div><div><span>New</span><b className="blue-text">12</b></div><div><span>Updated</span><b>28</b></div><div><span>Invalid</span><b className="orange-text">7</b></div></div><section className="panel table-panel"><div className="table-toolbar"><div className="search-box"><Search size={16} /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search recipients..." /></div><button className="filter-button"><Filter size={15} /> Filter <ChevronDown size={14} /></button><select className="select-filter" value={filter} onChange={e => setFilter(e.target.value)}><option>All</option><option>New</option><option>Updated</option><option>Delivered</option><option>Invalid</option></select></div><div className="table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Status</th><th>Last contacted</th><th>Added date</th><th /></tr></thead><tbody>{rows.map(r => <tr key={r.email}><td><strong>{r.name}</strong></td><td>{r.email}</td><td><StatusPill status={r.status} /></td><td>{r.contacted}</td><td>{r.added}</td><td><MoreHorizontal size={17} className="more" /></td></tr>)}</tbody></table>{!rows.length && <div className="empty-state"><Search size={22} /><strong>No recipients found</strong><span>Try adjusting your search or filter.</span></div>}</div><div className="table-footer">Showing {rows.length} of 1,284 recipients <span>Page 1 of 129 <ChevronRight size={14} /></span></div></section></>
}
function HistoryPage() { const [q, setQ] = useState(''); const filtered = history.filter(x => `${x.recipient} ${x.email} ${x.campaign}`.toLowerCase().includes(q.toLowerCase())); return <><div className="page-intro"><div><h2>Email history</h2><p className="muted">Track every message sent from your workspace.</p></div><button className="secondary-button"><FileText size={16} /> Export history</button></div><section className="panel table-panel"><div className="table-toolbar"><div className="search-box"><Search size={16} /><input value={q} onChange={e => setQ(e.target.value)} placeholder="Search history..." /></div><button className="filter-button"><Filter size={15} /> Status <ChevronDown size={14} /></button></div><div className="table-wrap"><table><thead><tr><th>Recipient</th><th>Email</th><th>Campaign</th><th>Status</th><th>Sent at</th><th /></tr></thead><tbody>{filtered.map(x => <tr key={`${x.email}-${x.at}`}><td><strong>{x.recipient}</strong></td><td>{x.email}</td><td>{x.campaign}</td><td><StatusPill status={x.status} /></td><td>{x.at}</td><td><MoreHorizontal size={17} className="more" /></td></tr>)}</tbody></table></div></section></> }
function CampaignsPage({ onCreate }: { onCreate: () => void }) { return <><div className="page-intro"><div><h2>Campaigns</h2><p className="muted">Create, manage, and review your email campaigns.</p></div><button className="primary-button" onClick={onCreate}><Plus size={17} /> Create campaign</button></div><section className="panel table-panel"><div className="table-toolbar"><div><h3>All campaigns</h3><p className="muted">{campaigns.length} campaigns in your workspace</p></div><button className="filter-button"><Filter size={15} /> Filter <ChevronDown size={14} /></button></div><div className="table-wrap"><table><thead><tr><th>Campaign name</th><th>Subject</th><th>Recipients</th><th>Sent</th><th>Failed</th><th>Status</th><th>Created</th></tr></thead><tbody>{campaigns.map(c => <tr key={c.name}><td><div className="table-campaign"><span className="campaign-mark small"><Mail size={15} /></span><strong>{c.name}</strong></div></td><td>{c.subject}</td><td>{c.recipients}</td><td>{c.sent}</td><td>{c.failed}</td><td><StatusPill status={c.status} /></td><td>{c.date}</td></tr>)}</tbody></table></div></section></> }
function CreateCampaign({ close }: { close: () => void }) { const [sent, setSent] = useState(false); const [sending, setSending] = useState(false); const [teamLeader, setTeamLeader] = useState('Morgan Lee'); const [message, setMessage] = useState('Hi {name},\n\nYour team leader, {teamLeaderName}, has a few exciting updates to share with you.\n\nThanks,\nThe MailFlow team'); function send() { setSending(true); setTimeout(() => { setSending(false); setSent(true) }, 1400) } return <div className="modal-backdrop"><div className="campaign-modal"><div className="modal-head"><div><p className="eyebrow">New campaign</p><h2>{sent ? 'Campaign sent' : 'Create campaign'}</h2></div><button className="icon-button" onClick={close} aria-label="Close"><X size={19} /></button></div>{sent ? <div className="send-success"><div className="success-check"><Check size={28} /></div><h3>Your campaign is on its way</h3><p>1,284 emails are being delivered. You can track progress in Email history.</p><button className="primary-button" onClick={close}>Done</button></div> : <div className="modal-body"><div className="form-column"><label>Campaign name<input defaultValue="August product update" /></label><label>Recipients<select><option>All recipients (1,284)</option><option>New recipients (12)</option></select></label><label>Team leader name<input value={teamLeader} onChange={e => setTeamLeader(e.target.value)} placeholder="Enter team leader name" /></label><label>Email subject<input defaultValue="What’s new in MailFlow" /></label><label>Message<textarea value={message} onChange={e => setMessage(e.target.value)} rows={8} /><span className="field-hint">Use {'{name}'}, {'{email}'} and {'{teamLeaderName}'} to personalize your message.</span></label><button className="secondary-button test-button"><Send size={15} /> Send test email</button></div><div className="preview-column"><p className="eyebrow">Live preview</p><div className="email-preview"><div className="email-brand"><span className="brand-glyph"><Mail size={15} /></span> MailFlow</div><div className="email-content">{message.replace('{name}', 'Olivia').replace('{teamLeaderName}', teamLeader || 'your team leader').replace('{email}', 'olivia@example.com').split('\n').map((line, i) => <p key={i}>{line || ' '}</p>)}</div><div className="email-footer">Sent with MailFlow</div></div></div></div>} {!sent && <div className="modal-foot"><button className="secondary-button" onClick={close}>Cancel</button><button className="primary-button" onClick={send} disabled={sending}>{sending ? <Loader2 className="spin" size={16} /> : <Send size={16} />} {sending ? 'Sending...' : 'Send campaign'}</button></div>}</div></div> }
export default function Page() { const [page, setPage] = useState<PageKey>('Dashboard'); const [mobile, setMobile] = useState(false); const [create, setCreate] = useState(false); const nav = [{ label: 'Dashboard', icon: LayoutDashboard }, { label: 'Recipients', icon: Users }, { label: 'Campaigns', icon: Mail }, { label: 'History', icon: Clock3 }]; return <main className="app-shell"><aside className={`sidebar ${mobile ? 'open' : ''}`}><div className="brand"><span className="brand-glyph"><Mail size={16} /></span><span>MailFlow</span></div><div className="workspace-switch"><span className="workspace-avatar">JD</span><span><b>Jamie’s workspace</b><small>Personal workspace</small></span><ChevronDown size={15} /></div><nav><p className="nav-label">Workspace</p>{nav.map(({ label, icon: Icon }) => <button key={label} className={page === label ? 'active' : ''} onClick={() => { setPage(label as PageKey); setMobile(false) }}><Icon size={17} />{label}{label === 'Recipients' && <span className="nav-count">12</span>}</button>)}</nav><div className="sidebar-bottom"><button><Settings size={17} /> Settings</button><div className="upgrade-card"><Sparkles size={16} /><strong>Unlock more with Pro</strong><span>Send unlimited campaigns and more.</span><button>Upgrade plan <ArrowUpRight size={14} /></button></div><div className="user-row"><span className="avatar">JD</span><span><b>Jamie Davis</b><small>jamie@acme.co</small></span><MoreHorizontal size={17} /></div></div></aside><section className="main-area"><Topbar title={page} onMenu={() => setMobile(!mobile)} onCreate={() => setCreate(true)} /><div className="page-content">{page === 'Dashboard' && <Dashboard onCreate={() => setCreate(true)} />}{page === 'Recipients' && <RecipientsPage />}{page === 'Campaigns' && <CampaignsPage onCreate={() => setCreate(true)} />}{page === 'History' && <HistoryPage />}</div></section>{create && <CreateCampaign close={() => setCreate(false)} />}</main> }
